// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PruebaFall.Model;

namespace PruebaFall.Migrations
{
    [DbContext(typeof(ContextoBD))]
    [Migration("20210606183557_MigracionIni")]
    partial class MigracionIni
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("PruebaFall.Model.Cancelacion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("DatoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("dup_f12")
                        .HasColumnType("INTEGER");

                    b.Property<int>("dup_oc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("estado_cd")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("estado_linea")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("estado_orden_oms")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("f12")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("monto_total_linea")
                        .HasColumnType("INTEGER");

                    b.Property<string>("oc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("precio_despacho")
                        .HasColumnType("INTEGER");

                    b.Property<string>("sku_linea")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("tipo_abastecimiento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DatoId");

                    b.ToTable("Cancelaciones");
                });

            modelBuilder.Entity("PruebaFall.Model.Dato", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("cc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("estado")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("f12")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("oc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("sku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Datos");
                });

            modelBuilder.Entity("PruebaFall.Model.Cancelacion", b =>
                {
                    b.HasOne("PruebaFall.Model.Dato", "Dato")
                        .WithMany("Cancelaciones")
                        .HasForeignKey("DatoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dato");
                });

            modelBuilder.Entity("PruebaFall.Model.Dato", b =>
                {
                    b.Navigation("Cancelaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
